### ISSUE TITLE
Rename this repo to meta?

### ISSUE THREAD

**Issue by ulysses4ever** [haskell-actions/meta#3]
To follow, e.g. https://github.com/haskell/meta/

**Comment by andreasabel** [comment]
I am open to this.  

Are there more examples? (https://github.com/search?q=meta&type=repositories)
- https://github.com/whatwg/meta
- https://github.com/executablebooks/meta
- https://github.com/dojo/meta
- https://github.com/monero-project/meta
- https://github.com/beerjs/meta
- https://github.com/ampproject/meta
- https://github.com/BitcoinDesign/Meta

Counterexamples (other uses of `meta`):
- https://github.com/mateodelnorte/meta
- https://github.com/skypjack/meta
- https://github.com/ericniebler/meta
- https://github.com/jiangshanmeta/meta
- https://github.com/miscreant/meta
- https://github.com/srossross/Meta

Other:
- https://github.com/apertium/organisation

**Comment by ulysses4ever** [comment]
Right. My suspicion is that there's a lot of variation in this space, so probably there's no definitive guideline. It just feels natural for `haskell-actions` to follow the `haskell`'s example.

**Comment by andreasabel** [comment]
Ok, done!
