### ISSUE TITLE
Allow packages to be public

### ISSUE THREAD

**Issue by chungyc** [haskell-actions/meta#4]
For those who would like to publish packages, can we allow repositories to change the visibility to their packages?  When I try to edit package visibility with haskell-actions/hlint-scan, they tell me that "Setting is disabled by organization administrators.".

For context, I just rewrote the [haskell-actions/hlint-scan](https://github.com/haskell-actions/hlint-scan) action as a Docker container action for [reasons](https://github.com/haskell-actions/hlint-scan/issues/7).  However, it currently needs to build its Docker image every time, which is really slow, so it should really use a prebuilt Docker image.  Unfortunately, the only repository which can use the prebuilt Docker image is haskell-actions/hlint-scan itself, because package visibility is private.

**Comment by andreasabel** [comment]
@chungyc Could you try again please?  I enabled public packages just now.

**Comment by chungyc** [comment]
Thanks!  I can make packages public now.
