### ISSUE TITLE
Consider logo for the haskell-actions organization

### ISSUE THREAD

**Issue by chungyc** [haskell-actions/meta#5]
The profile picture for the [haskell-actions organization](https://github.com/haskell-actions) is a rather lackluster blocky $\pi$.  Should there be consideration given for replacing it with something more Haskell-y?  E.g., https://wiki.haskell.org/Thompson-Wheeler_logo, with maybe a little modification in color or additional shapes to distinguish it from the [haskell organization](https://github.com/haskell).

**Comment by andreasabel** [comment]
Yes, definitely, contribution very welcome!

> with maybe a little modification in color or additional shapes to distinguish it from the [haskell organization](https://github.com/haskell).

Could also be a little addendum to the logo, maybe superscript "CI".

**Comment by chungyc** [comment]
I now have a proposal in https://github.com/haskell-actions/meta/pull/6.  I used a lightning bolt instead of a "CI" superscript to signify actions, since GitHub actions encompasses more than continuous integration, and also to avoid confusion with [haskell-ci](https://github.com/haskell-ci)'s profile picture.

I can't draw, so I edited the SVG by hand.
