### ISSUE TITLE
Do you want dep-haskell-stack to be transferred to this org?

### ISSUE THREAD

**Issue by stevemao** [haskell-actions/meta#8]
https://github.com/stevemao/dep-haskell-stack

Dependabot Haskell Stack
This action updates Haskell Stack dependencies to the latest LTS version.

- Bump Haskell Stack resolver
- Bump extra-deps
It will update the versions in both stack.yaml and stack.yaml.lock.

**Comment by mihaimaruseac** [comment]
I think that would be nice to have here

**Comment by andreasabel** [comment]
This seems like a brand new action, how does it work?
I mean, what is the secret sauce that updates `stack.yaml` to the latest resolver?
Can it also update `nightly` to the latest nightly?
Will it preserve an LTS that is "finished", like `18.28`?

**Comment by stevemao** [comment]
> how does it work?

It imitates how a real person would update the deps
- it gets the latest versions and updates stack.yaml. But instead of visiting the stackage website, it does API call
- run `stack build` to regen the lock file

> Can it also update nightly to the latest nightly?

can certainly add this feature easily.

>Will it preserve an LTS that is "finished", like 18.28?

Currently it will update it to the latest LTS. What should be the expected behaviour?

**Comment by andreasabel** [comment]
> Currently it will update it to the latest LTS. What should be the expected behaviour?

_Big_ LTS bumps like from `20.26` to `21.0` can bump the GHC major version also.  So, sometimes one only wants to make minor bumps which keep the same major GHC version.

E.g. for Agda we maintain `stack-${GHC_VERSION}.yaml` files (e.g. [`stack-9.4.7.yaml`](https://github.com/agda/agda/blob/1630aee9a3250886dfe9b3d218310243007d9266/stack-9.4.7.yaml)) which would be nice to bump within the same GHC version automatically.  I don't know if such thing would be possible easily by an API call.

Ok, these are more features, but I guess your basic feature (just bump `stack.yaml` to the latest LTS) is also what some users would want.

**Comment by stevemao** [comment]
I agree
