### ISSUE TITLE
Accepting GitHub Marketplace Developer Agreement

### ISSUE THREAD

**Issue by chungyc** [haskell-actions/meta#9]
When trying to [release](https://github.com/haskell-actions/hlint-scan/releases/tag/untagged-822a02549608c688a8f3) a new version of https://github.com/haskell-actions/hlint-scan, I encounter a checkbox that I cannot click:

> **Publish this release to the GitHub Marketplace**
> 
> haskell-actions must accept the GitHub Marketplace Developer Agreement. Contact an org admin to accept it.

I think I could click it before, and the previous version is in fact [on the Marketplace](https://github.com/marketplace/actions/scan-code-with-hlint), so accepting the agreement by the organization administrators may be a new requirement.  I do not know where this can be done, although I presume it can be done somewhere in the organization settings.

Can someone approve the agreement? Alternatively if we should not, can someone let me know and document it on https://github.com/haskell-actions/meta?

**Comment by andreasabel** [comment]
I didn't have any luck with these agreements since they wanted a company as partner and not an individual.

Since you are one of the stakeholders in this organization, I made you a co-owner just now.

Please try again if you can now approve the agreement.  If this is not possible still, we might have to reach out for haskell.org if they can help us to act as a partner for Github.

**Comment by chungyc** [comment]
Fortunately, this only required accepting the agreement in a popup, which I now did.  Thanks!

For reference, this is the agreement: https://docs.github.com/en/site-policy/github-terms/github-marketplace-developer-agreement

**Comment by mihaimaruseac** [comment]
Thank you! This has stopped me form uploading the other hlint actions but I didn't get time at the time to investigate further and then I forgot.

**Comment by andreasabel** [comment]
> Fortunately, this only required accepting the agreement in a popup,

Oh, I think I confused this with trying to change GitHub's model workflow for Haskell, which is badly outdated.  There, I am stuck on not being able to become a GitHub partner...
- https://github.com/haskell-actions/setup/issues/59
